---
- name: Define VMs
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', '{{ item.value.vm_template }}.xml.j2') }}"
  when: "item.key not in existing_vms.list_vms"

- name: Create second disk images if needed
  ansible.builtin.command: |
    qemu-img create -q -f {{ item.value.file_type }} \
    {{ libvirt_pool_dir }}/{{ item.key }}-vdb.{{ item.value.file_type }} {{ item.value.second_hdd_size }}
  become: true
  when: item.value.second_hdd | bool == true

- name: Attach second disk image to domain
  ansible.builtin.command: |
    virsh -c qemu:///system attach-disk {{ item.key }} \
    --source "{{ libvirt_pool_dir }}/{{ item.key }}-vdb.{{ item.value.file_type }}" \
    --target vdb \
    --subdriver qcow2 \
    --persistent
  become: true
  when: item.value.second_hdd|bool == true

- name: Ensure VMs are startet
  community.libvirt.virt:
    name: "{{ item.key }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 15
  delay: 2
